dataset:
    type: 'SyntheticShapes'
    primitives: 'all'
    length: 3000
    preprocessing:
        blur_size: 21
        additional_ir_blur: True
        additional_ir_blur_size: 51
    augmentation:
        photometric:
            enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 0.15}
                random_contrast: {strength_range: [0.3, 1.8]}
                additive_gaussian_noise: {stddev_range: [0, 0.06]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.8]
                    kernel_size_range: [250, 350]
                motion_blur: {max_kernel_size: 7}
        homographic:
            enable: true
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                patch_ratio: 0.85
                max_angle: 1.57  # 3.14
                allow_artifacts: true
                translation_overflow: 0.05
            valid_border_margin: 0
            border_reflect: true

model:
    type: 'MultiPoint'
    multispectral: true
    descriptor_head: false
    descriptor_size: 256
    intepolation_mode: bilinear
    normalize_descriptors: true
    final_batchnorm: true
    reflection_pad: true
    bn_first: false

loss:
    type: 'MultiPointLoss'
    detector_loss: true
    detector_use_cross_entropy: true
    descriptor_loss: false

training:
    n_epochs: 100
    learningrate: 1e-4
    batchsize: 32
    num_worker: 4
    allow_gpu: true
    use_writer: true
    output_directory: '/tmp/superpoint'
    save_every_n_epoch: 5
    validation:
        compute_validation_loss: false

prediction:
    allow_gpu: true
    num_worker: 4
    batchsize: 10
    detection_threshold: 0.015
    nms: 4
    cpu_nms: false
    topk: 0
